* # BootCamp Week 3 - NumPy Notes 

* NumPy is the library that gives Python its ability to work with data at speed. 

In [1]:
import numpy as np

# Creating array

In [2]:
array1 = np.array([1,2,3])                               # creating a 1D array
array1

array([1, 2, 3])

In [3]:
array2 = np.array([(1,2,3,4),(7,8,9,10)],dtype=int)       #creating a 2D array
array2

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [4]:
arr3 = np.zeros(5,dtype = int) # 1D array of length 5 all values 0
arr3

array([0, 0, 0, 0, 0])

In [5]:
arr4 = np.ones((7,8),dtype= int) # 7x array with all values 1
arr4

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
arr5 = np.eye(5,dtype = int) # 5x5 array of 0 with 1 on diagonal (Identity matrix)
arr5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [7]:
arr6 = np.linspace(0,100,10) # Array of 10 evenly divided values from 0 to 100
arr6


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [8]:
arr7 = np.arange(0,10,3) # Array of values from 0 to less than 10 with step 3 (eg [0,3,6,9])
arr7

array([0, 3, 6, 9])

In [9]:
arr8 = np.full((2,3),8) # 2x3 array with all values 8
arr8

array([[8, 8, 8],
       [8, 8, 8]])

In [10]:
arr9 = np.random.rand(4,5) # 4x5 array of random floats between 0-1
arr9

array([[2.43755779e-01, 1.85437795e-01, 4.65673757e-01, 7.21399214e-01,
        8.12643119e-02],
       [3.54674602e-01, 5.19499869e-01, 7.80591967e-04, 9.38571191e-03,
        6.14944594e-01],
       [4.11669240e-01, 3.16124462e-01, 8.71899026e-01, 2.35295412e-01,
        9.00861746e-01],
       [7.53522047e-01, 7.29749051e-01, 8.07597625e-01, 7.98765358e-01,
        9.12318982e-01]])

In [11]:
arr10 = np.random.rand(6,7)*100 # 6x7 array of random floats between 0-100
arr10

array([[90.49149486, 10.25466203, 51.42440989, 19.57769832, 90.63387419,
        65.46186959, 30.56172067],
       [50.62208235, 30.38767497, 34.25892086, 97.20674413, 65.5473116 ,
        75.81144575, 10.96659223],
       [21.52415798, 44.73891554,  7.05935663, 22.84920093, 24.31197772,
        10.93864973, 35.72996607],
       [91.71294225, 57.84833393,  7.71501335, 60.86138255,  2.46026304,
        30.8756731 , 30.64736392],
       [70.13943581, 81.08153232, 41.1121331 , 84.94939011, 66.70148373,
        95.51367831, 11.4925176 ],
       [85.57689507, 53.30917643,  5.48034267,  8.08405085, 23.45351044,
         5.5116092 ,  5.59715911]])

In [12]:
arr11 = np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0-4
arr11

array([[3, 0, 2],
       [1, 2, 1]])

# Properties

* size – Returns number of elements in array
* shape – Returns dimensions of array(rows, columns)
* array.dtype – Returns type of elements in array

# Arithmetic Operations

* Addition: np.add(a,b)
* Subtraction:np.subtract(a,b)
* Multiplication: np.multiply(a,b)
* Division: np.divide(a,b)
* Exponentiation: np.exp(a)
* Square Root: np.sqrt(b)

# Operations

* Copying

* Size

In [13]:
array2.size #  Returns number of elements in array2

8

In [14]:
array2.shape # Returns dimensions of arr (rows,columns)


(2, 4)

* DataType

In [15]:
array2.dtype # Returns type of elements in arr

dtype('int32')

In [16]:
array = np.array([(1,2,3,4),(7,8,9,10)],dtype=int) 
np.copy(array) #Copies array to new memory array.


array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

* type casting

In [17]:
array1.astype(str) # Convert array1 elements to type dtype

array(['1', '2', '3'], dtype='<U11')

* Array to list

In [18]:
array2.tolist() # Convert array2 to a Python list

[[1, 2, 3, 4], [7, 8, 9, 10]]

* Sorting

In [19]:
array= np.array([1,2,3,4,5,6])
array.sort() # Sorts array
array.sort(axis=0) # Sorts specific axis of array
array.reshape(2,3) # Reshapes array to 2 rows, 3 columns without changing data.

array([[1, 2, 3],
       [4, 5, 6]])

* Adding

In [20]:
values = [125,124,6,7,3]
np.append(array,values) # Appends values to end of array
np.insert(array,4,values) # Inserts values into array before index 4

array([  1,   2,   3,   4, 125, 124,   6,   7,   3,   5,   6])

* Removing

In [21]:
np.delete(array,2,axis=0) # Deletes row on index 2 of array

array([1, 2, 4, 5, 6])

* Combining

In [22]:
array1 = np.array([5,15,25,35])
array2 = np.array([10,20,30,40])
np.concatenate((array1,array2),axis=0) # Adds array2 as rows to the end of array1

array([ 5, 15, 25, 35, 10, 20, 30, 40])

* Splitting

In [23]:
np.split(array,3) # Splits array into 3 sub-arrays

[array([1, 2]), array([3, 4]), array([5, 6])]

* Indexing

In [24]:
array2[0]=5 # Assigns array element on index 0 the value 5

* Slicing

In [46]:
array4 = np.arange(0,16,1).reshape(4,4)
array4[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Statistics

In [47]:
np.mean(array4,axis=0) # Returns mean along specific axis

array([6., 7., 8., 9.])

In [48]:
array4.sum() # Returns sum of arr

120

In [49]:
array4.min() # Returns minimum value of arr

0

In [50]:
array4.max(axis=0) # Returns maximum value of specific axis

array([12, 13, 14, 15])

In [51]:
np.var(array4) #Returns the variance of array

21.25

In [52]:
np.std(array4,axis=1) # Returns the standard deviation of specific axis

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])